---
- name: Check if server proxy file exists
  ansible.builtin.stat:
    path: /etc/default/rke2-server
  register: server_proxy_file
  when: "'server_nodes' in group_names"

- name: Check if agent proxy file exists
  ansible.builtin.stat:
    path: /etc/default/rke2-agent
  register: agent_proxy_file
  when: "'agent_nodes' in group_names"

- name: Handle RKE2 server proxy configuration
  when: "'server_nodes' in group_names"
  block:
    - name: Create RKE2 server proxy environment file
      ansible.builtin.template:
        src: rke2-service-env.j2
        dest: /etc/default/rke2-server
        owner: root
        group: root
        mode: "0644"
      when: rke2_http_proxy | default('') | length > 0
      notify: Reload systemd

    - name: Remove RKE2 server proxy environment file if not needed
      ansible.builtin.file:
        path: /etc/default/rke2-server
        state: absent
      when:
        - rke2_http_proxy | default('') | length == 0
        - server_proxy_file.stat.exists | default(false)
      notify: Reload systemd

- name: Handle RKE2 agent proxy configuration
  when: "'agent_nodes' in group_names"
  block:
    - name: Create RKE2 agent proxy environment file
      ansible.builtin.template:
        src: rke2-service-env.j2
        dest: /etc/default/rke2-agent
        owner: root
        group: root
        mode: "0644"
      when: rke2_http_proxy | default('') | length > 0
      notify: Reload systemd

    - name: Remove RKE2 agent proxy environment file if not needed
      ansible.builtin.file:
        path: /etc/default/rke2-agent
        state: absent
      when:
        - rke2_http_proxy | default('') | length == 0
        - agent_proxy_file.stat.exists | default(false)
      notify: Reload systemd
