---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: rke2-render
    image: "${MOLECULE_IMAGE:-geerlingguy/docker-debian12-ansible:latest}"
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: ""
    groups:
      - server_nodes

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
  inventory:
    hosts:
      all:
        vars:
          ansible_user: root

verifier:
  name: ansible
