---
- name: Restart rke2-server
  ansible.builtin.systemd_service:
    name: rke2-server
    state: restarted
    daemon_reload: true

- name: Restart rke2-agent
  ansible.builtin.systemd_service:
    name: rke2-agent
    state: restarted
    daemon_reload: true

- name: Restart keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted

- name: Apply CIS sysctl
  ansible.builtin.command: sysctl -p /etc/sysctl.d/60-rke2-cis.conf
  changed_when: true
