---
name: Release Drafter

permissions:
  contents: write
  pull-requests: read

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e  # v7
        with:
          config-name: RELEASE_DRAFTER.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
